config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  get  'home/index'
  root 'pins#index'
  get  'home/about'
  get  'devise/sessions/new'
  get  'devise/passwords/edit'
  get  'devise/passwords/new'
  get  'devise/registrations/edit'
  get  'devise/registrations/new'
  get  'devise/confirmations/new'
  get  'devise/mailer/confirmation'
  get  'devise/mailer/password_change'
  get  'devise/mailer/reset_password_instructions'
  get  'devise/mailer/unlock_instructions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
belongs_to :user
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100"}
validates_attachment_content_type :image, :content_type => /\image\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
    def about
    end
    
    def edit
    end
    
    def sign_up
    end
    
    def users
    end
    
    
    def cancel
    end

    def password
    end
    
    def sign_in
    end
    
    def sign_out
    end    
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def correct_user
    @pin=current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
<div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">My Project</a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav">
<li><%= link_to 'Home', root_path, class: 'btn btn-primary' %></li>
<li><%= link_to 'About Me', home_about_path, class: 'btn btn-primary' %></li>
<% if user_signed_in? %>
<%= javascript_include_tag :defaults %>
<li><%= link_to 'LIST PINS', pins_path, class: 'btn btn-primary' %></li>
<li><%= link_to 'EDIT PROFILE', edit_user_registration_path, class: 'btn btn-primary' %></li>
<li><%= link_to 'SIGN OUT', destroy_user_session_path, class: 'btn btn-primary',  :method => :delete %></li>
<% else %>
<li><%= link_to 'LOGIN', new_user_session_path, class: 'btn btn-primary'%></li>
<li><%= link_to 'JOIN', new_user_registration_path, class: 'btn btn-primary' %></li>
<% end %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/home/_index.html.erb
<div class="jumbotron center">
<h1>Welcome to my Ruby Site</h1>
<% if user_signed_in? %>
<%= link_to 'Logout',  destroy_user_session_path, class: 'btn btn-primary' %>
<%= link_to 'Edit Profile',  edit_user_registration_path, class: 'btn btn-primary' %>
<%= link_to 'List Pins', pins_path, class: 'btn btn-primary' %>
<% else %>
<%= link_to 'Login',  new_user_session_path, class: 'btn btn-primary' %>
<%= link_to 'Join',  user_registration_path, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/home/about.html.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="Keywords" content="CIW, Web Foundations Associate, Example">
<meta name="Description" content="For the CIW Web Foundations Associate courses">
<meta charset="utf-8">
<title>DNorwood-InternetCertified</title>
</head>
<body style="color: rgb(255, 153, 0); background-color: rgb(0, 102, 0);" alink="#000099" link="#000099" vlink="red">
<h1 style="text-align: center;"><span style="font-weight: bold;">Donavon Marcel Norwood</span>
</h1><div style="text-align: center;"><span style="font-weight: bold;"> Internet Certified and Ready to Succeed!</span><br/><br/>
<hr style="width: 100%; height: 2px;"><div style="text-align: left;"><span style="font-style: italic;"><br/>
</span>
<table style="text-align: left; width: 100%;" border="1" cellpadding="2" cellspacing="2">
<tbody>
<tr><th><span style="font-style: italic;">Certifications</span>:</th><th style="width: 50%;"><span style="font-style: italic;">Internet Skills</span>:
</th></tr>
<tr><td align="undefined" valign="undefined">
<ul>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/internet-business-associate">CIW Internet Business Associate</a>
</li>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/site-development-associate">CIW Site Development Associate</a>
</li>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/network-technology-associate">CIW Network Technology Associate</a>
</li>
<li>
<a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/web-foundations-associate">CIW Web Foundations Associate</a></li></ul>
</td>
<td align="undefined" valign="undefined">
<ol>
<li>Web browsers, mobile devices, SMS, e-mail, FTP, social networking, ecommerce</li>
<li>Web page authoring in HTML5, CSS, and simple JavaScript</li>
<li>Basic networking components, protocols and server configuration&nbsp;</li>
<li>Basic security concepts and virus protection</li>
<li>Project management skills for individual and team job tasks</li>
</ol>
</td>
</tr>
</tbody>
</table>
<span style="font-style: italic;"></span><span style="font-style: italic;"></span><br/>
<hr style="width: 100%; height: 2px;"><div style="text-align: center;">
</body>
</html>

app/views/home/index.html.erb
<div class="jumbotron center">
<h1>Welcome to my Ruby Site</h1>
<% if user_signed_in? %>
<%= link_to 'Logout',  destroy_user_session_path, class: 'btn btn-primary' %>
<%= link_to 'Edit Profile',  edit_user_registration_path, class: 'btn btn-primary' %>
<%= link_to 'List Pins', pins_path, class: 'btn btn-primary' %>
<% else %>
<%= link_to 'Login',  new_user_session_path, class: 'btn btn-primary' %>
<%= link_to 'Join',  user_registration_path, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/home/myBackup/_article.html.erb
<article>
   <div>
    <div>
        <h1><a href="https://dnorwood.herokuapp.com/home/about">About Me:</h1></a><br/> 
        <p>My name is <a href="http://mymobileinfo.x10.bz/myResume/resumeDonavonNorwood.pdf"> Donavon Marcel Norwood</a>, and I am a student at the <a href="http://www.stridecenter.org/">Stride Center</a> in Oakland, CA<br/>
        Currently I am enrolled in the <a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/site-development-associate">Coding99</a> program.  The program teaches us students the basic funda-<br>
        mentals of HTML 5, CSS 3, PHP, Ruby on Rails, and job development.  My instructtor name is Deana Lawrence.</p><br/>
    </div>
  </div>
</article>

app/views/home/myBackup/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    <a class="navbar-brand" href="mailto:dnorwood112870@gmail.com">myEmail</a>
    <a class="navbar-brand" href="http://mymobileinfo.x10.bz/">myMobileInfo</a>
    <a class="navbar-brand" href="http://mymobileinfo.x10.bz/myHabitat/CCYP/syb.htm">myPortfolio</a>
    <a class="navbar-brand" href="http://www.slideshare.net/dmnor510">myPresentations</a>
    <a class="navbar-brand" href="https://www.scribd.com/user/5934178/dmnor510">myResearch</a>
    <a class="navbar-brand" href="http://mymobileinfo.x10.bz/myResume/resumeDonavonNorwood.pdf">myResume</a>
    <a class="navbar-brand" href="http://mymobileinfo.x10.bz/myStrideCenter.html">myStrideCenter</a>
    <a class="navbar-brand" href="https://dnorwood.herokuapp.com/">Home</a>
    </div>
  </div>
</nav>
  <%= link_to 'Home', root_path %>
  <%= link_to 'About Us', home_about_path %>

app/views/home/myBackup/about.html.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="Keywords" content="CIW, Web Foundations Associate, Example">
<meta name="Description" content="For the CIW Web Foundations Associate courses">
<meta charset="utf-8">
<title>DNorwood-InternetCertified</title>
</head>

/* Please he me somebody! */

<body style="color: rgb(255, 153, 0); background-color: rgb(0, 102, 0);" alink="#000099" link="#000099" vlink="red">
<h1 style="text-align: center;"><span style="font-weight: bold;">Donavon Marcel Norwood</span>
</h1><div style="text-align: center;"><span style="font-weight: bold;"> Internet Certified and Ready to Succeed!</span><br/><br/>
<hr style="width: 100%; height: 2px;"><div style="text-align: left;"><span style="font-style: italic;"><br/>
</span>
<table style="text-align: left; width: 100%;" border="1" cellpadding="2" cellspacing="2">
<tbody>
<tr><th><span style="font-style: italic;">Certifications</span>:</th><th style="width: 50%;"><span style="font-style: italic;">Internet Skills</span>:
</th></tr>
<tr><td align="undefined" valign="undefined">
<ul>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/internet-business-associate">CIW Internet Business Associate</a>
</li>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/site-development-associate">CIW Site Development Associate</a>
</li>
<li><a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/network-technology-associate">CIW Network Technology Associate</a>
</li>
<li>
<a href="https://www.ciwcertified.com/ciw-certifications/web-foundations-series/web-foundations-associate">CIW Web Foundations Associate</a></li></ul>
</td>
<td align="undefined" valign="undefined">
<ol>
<li>Web browsers, mobile devices, SMS, e-mail, FTP, social networking, ecommerce</li>
<li>Web page authoring in HTML5, CSS, and simple JavaScript</li>
<li>Basic networking components, protocols and server configuration&nbsp;</li>
<li>Basic security concepts and virus protection</li>
<li>Project management skills for individual and team job tasks</li>
</ol>
</td>
</tr>
</tbody>
</table>
<span style="font-style: italic;"></span><span style="font-style: italic;"></span><br/>
<hr style="width: 100%; height: 2px;"><div style="text-align: center;">
</body>
</html>

app/views/home/myBackup/index.html.erb
<!DOCTYPE html>
<head>
  <title>Donavon's first Ruby Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = "container">
  <%= render 'home/article' %><br/>
<h1>DNorwood's Ruby site</h1><br/>
<p>I hope you enjoy my site!!! More information to come!!!
   In this area of this page, will be video step-by-step 
   instructions<br/> on how to install, configure and use git, Rails,
   and Ruby.</p></div><br/> 
<%= link_to 'About Us', home_about_path, class: 'btn-success' %><br/> 
<%= link_to 'Home', home_index_path, class: 'btn-info' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial=scale=1, maximum-scale=1" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'home/header' %> 
<div class="container">
 <% flash.each do |name, msg| %>
 <%= content_tag( :div, msg, class: "alert alert-info") %>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for@pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
 <div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: "form-control" %>
</div>
<div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
  </div>
  <div class="panel-footer">
  </div>  
  </div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<%= render '/home/index' unless user_signed_in? %>
<div class="panel panel-primary">
<div class="panel-heading"><h1>LISTING PINS</h1></div>
 <div class="panel-body">
   <div id="pin" class="transitions-enabled">
     <%= @pins.each do |pin| %>
       <div class="box">
       <%= pin.description %>
       <%= image_tag pin.image.url(:thumb) %><br/>
       <%= link_to 'Show', pin, class: 'btn btn-primary' %>
       <% if pin.user == current_user %>
       <%= link_to 'Edit', edit_pin_path(pin), class: 'btn btn-primary' %>
       <%= link_to 'Destroy', pin, method: :delete, class: 'btn btn-primary', data: { confirm: 'Are you sure?' } %>
       <% end %>
      </div>       
       <% end %>
       </div>
       </div>
 <div class="panel-footer"><%= link_to 'New Pin', new_pin_path, class: 'btn btn-primary' %></div>
</div>
<div class="center">
<%= will_paginate @pins, renderer: BootstrapPagination::Rails %></div>

 

app/views/pins/new.html.erb
<h1>NEW PIN</h1>
<%= render 'form', pin: @pin %>
<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %></div>
      <div class="panel-body">
      
          <strong><%= @pin.description %></strong><br/>
          <%= @pin.user.name %><br/>
        
        <% if @pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(@pin) %> |
        <% end %>
          <%= link_to 'Back', pins_path %>

      </div>
    </div>
  </div>
</div>

        
  